import Card from "@/components/marcas/card"
import type { Metadata } from "next"
import { marcas } from "@/data/marcas"
import NuestrasMarcas from "@/components/marcas/nuestrasMarcas"

export const metadata: Metadata = {
  title: "Pricing Page",
  description: "Generated by Gerald",
  keywords: ["pricing", "page", "nextjs"],
}


export default function MarcasPage() {
  return (
    <>
      <NuestrasMarcas />
      <div className="flex flex-wrap justify-center p-[8px] mt-4 gap-1">
        {marcas.map((marca, index) => (
          <Card key={index} img={marca.img} description={marca.description} />
        ))}
      </div>
      </>
  )
}
