import Card from "@/components/marcas/card"
import type { Metadata } from "next"
import { marcas } from "@/data/marcas"
import SeccionBody from "@/components/ui/SeccionBody/SeccionBody"

export const metadata: Metadata = {
  title: "Pricing Page",
  description: "Generated by Gerald",
  keywords: ["pricing", "page", "nextjs"],
}


export default function MarcasPage() {
  return (
    <>
      <SeccionBody
        img="https://www.rabimport.com/image/icono-marcas.png"
        palabra1="Nuestras "
        palabra2="marcas"
      />

      <div className="max-w-6xl mx-auto flex flex-wrap justify-center gap-4 px-4 py-8">
        {marcas.map((marca, index) => (
          <Card key={index} img={marca.img} description={marca.description} />
        ))}
      </div>

    </>
  )
}
