
import type { Metadata } from "next";
import Slider from "../../../components/inicio/slider";
import AlianzaEmpresasItem from "../../../components/inicio/Seccion-Alianzas";
import Card from "../../../components/blogs/card";
import SeccionBody from "../../../components/ui/SeccionBody/SeccionBody";
import { marcas } from "../../../data/marcas";
import { asesores } from "../../../components/inicio/data";
import { testimonios } from "../../../components/inicio/Testimonios";
import { blogs } from "@/data/blogs/data";


export const metadata: Metadata = {
  title: "RUA Maquinas",
  description: "Generated by Geral",
  keywords: ["about", "page", "nextjs"],
  authors: [{ name: "Geraldhine" }],
};

export default function HomePage() {
  return (

    <div className="mr-[20px] ml-[20px] sm:mr-[20px] sm:ml-[20px] md:mr-[40px] md:ml-[40px] lg:mr-[80px] lg:ml-[80px]">
      <div className="mt-[20px] mb-[20px]">
        <hr />
      </div>

      <SeccionBody
        img={"https://www.rabimport.com/image/icon-asesores.png"}
        palabra1={"Nuestros"}
        palabra2={"Asesores"}
      />
      <Slider arreglo={asesores} tipo="asesores" />
      <div className="mt-[20px] mb-[20px]">
        <hr />
      </div>

      <SeccionBody
        img={"https://www.rabimport.com/image/icon-servicios.png"}
        palabra1={"Alianzas"}
        palabra2={"de empreas especializadas a su servicio"}
      />
      <AlianzaEmpresasItem />
      <div className="mt-[20px] mb-[20px]">
        <hr />
      </div>
      <SeccionBody
        img={"https://www.rabimport.com/image/icon-testimonios.png"}
        palabra1={"Nuestros"}
        palabra2={"testimonios"}
      />
      <Slider arreglo={testimonios} tipo="testimonios" />
      <div className="mt-[20px] mb-[20px]">
        <hr />
      </div>
      <SeccionBody
        img={"https://www.rabimport.com/image/icon-blogs.png"}
        palabra1={"Nuestros"}
        palabra2={"blogs"}
      />

      <Card
        id={1}
        img={"https://rab-import-assets.s3.amazonaws.com/blogs/Blog4.jpg"}
        date={"2023-10-01"}
        title={"5 claves para un éxito empresarial en 2023 en la industria textil y de confección en Perú"}
        description={"El nuevo año está aquí y con él, nuevos desafíos y oportunidades para los emprendedores y empresarios de la industria textil y de confección en Perú. En este mercado altamente competitivo, es fundamental estar preparado para afrontar los cambios y retos que se presentan. Aquí presentamos cinco claves para tener éxito en 2023. Innovación y tecnificación: Con la llegada de la industria 4.0, es imprescindible adoptar nuevas tecnologías y procesos innovadores para mejorar la eficiencia, la calidad y la competitividad. Automatización, digitalización y uso de inteligencia artificial son sólo algunos ejemplos de cómo la tecnología puede ayudar a mejorar la producción y la productividad. Ahorro de costos: Ser eficiente en costos siempre será una clave para el éxito empresarial. En este sentido, es importante evaluar los gastos y buscar formas de optimizarlos, desde la reducción de gastos generales hasta la optimización del uso de materiales y recursos. Calidad y estandarización: Ofrecer productos de alta calidad es fundamental para mantener y atraer clientes. Además, la estandarización de procesos y productos puede ayudar a mejorar la eficiencia y a mantener la calidad constante. Conocimiento del mercado y del cliente: Conocer a fondo a los clientes y los nichos de mercado es clave para ofrecer productos y servicios que cumplan con sus necesidades y expectativas. Es importante estar al tanto de las tendencias y preferencias de los consumidores para poder innovar y ofrecer opciones atractivas. Fortalecimiento de la marca: Crear y fortalecer una marca es fundamental para destacarse en el mercado y para atraer y mantener a los clientes. Esto implica desarrollar una identidad y una imagen distintiva, así como una estrategia de marketing efectiva para promocionar la marca y los productos. En resumen, para tener éxito en 2023 en la industria textil y de confección en Perú, es importante adoptar nuevas tecnologías, ser eficiente en costos, ofrecer productos de alta calidad, conocer a fondo al mercado y a los clientes, y fortalecer la marca. Con una combinación de innovación, eficiencia, calidad y conocimiento del mercado."}
      />
      <div className="mt-[20px] mb-[20px]">
        <hr />
      </div>
      <SeccionBody
        img={"https://www.rabimport.com/image/icono-marcas.png"}
        palabra1={"Nuestras"}
        palabra2={"marcas"}

      />
      <Slider arreglo={marcas} tipo="marcas" />


    </div>
  );

}
