import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by Geral",
  keywords: ["about", "page", "nextjs"],
  authors: [{ name: "Geraldhine" }],
};  

export default function HomePage() {
  return (
    <>
    <span className="text-5xl text-center">Home Page</span>
    </>
  )
}
